networks:
  sniffly-net:
    driver: bridge
    attachable: true

volumes:
  postgres-data:

services:
  backend:
    image: ghcr.io/nrf24l01/sniffly/backend:latest
    restart: unless-stopped
    build:
      context: backend/
      dockerfile: Dockerfile
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8000/ping"]
      interval: 5s
      retries: 30
      timeout: 3s
      start_period: 3s
    expose:
      - "8000"
    env_file:
      - .env
    environment:
      - APP_HOST=:8000
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=he1loT1ver
      - POSTGRES_DB=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_SSLMODE=disable
      - POSTGRES_TIMEZONE=Europe/Moscow
      - REDIS_HOST=redis:6379
      - REDIS_PASSWORD=
      - REDIS_DB=0
      - PRODUCTION_ENV=true
      - NO_LOGS=true
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - sniffly-net

  analyzer:
    image: ghcr.io/nrf24l01/sniffly/analyzer:latest
    build:
      context: analyzer/
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PG_HOST=postgres
      - PG_USER=postgres
      - PG_PASSWORD=he1loT1ver
      - PG_DATABASE=postgres
      - PG_PORT=5432
      - PG_SSLMODE=disable
      - PG_TIMEZONE=Europe/Moscow
      - REDIS_HOST=redis:6379
      - REDIS_PASSWORD=
      - REDIS_DB=0
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=rmquser
      - RABBITMQ_PASSWORD=rmqpass
      - RABBITMQ_VHOST=/
      - CAPTURE_PACKETS_TOPIC=sniffed
      - GEOIP_CACHE_TTL=86400
      - GEOIP_CACHE_KEY_PREFIX="geoip-cache:"
      - PRODUCTION_ENV=true
    networks:
      - sniffly-net
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  capture-receiver:
    image: ghcr.io/nrf24l01/sniffly/capture_receiver:latest
    build:
      context: capture_receiver/
      dockerfile: Dockerfile
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "/usr/local/bin/grpc_health_probe", "-addr=127.0.0.1:50051"]
      interval: 5s
      retries: 5
    restart: unless-stopped
    environment:
      - PG_HOST=postgres
      - PG_USER=postgres
      - PG_PASSWORD=he1loT1ver
      - PG_DATABASE=postgres
      - PG_PORT=5432
      - PG_SSLMODE=disable
      - PG_TIMEZONE=Europe/Moscow
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=rmquser
      - RABBITMQ_PASSWORD=rmqpass
      - RABBITMQ_VHOST=/
      - CAPTURE_REFLECTION_ENABLED=false
      - CAPTURE_APP_HOST=:50051
      - CAPTURE_PACKETS_TOPIC=sniffed
      - CAPTURE_PING_ENABLED=true
      - PRODUCTION_ENV=true
    expose:
      - "50051"
    networks:
      - sniffly-net
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  frontend:
    image: ghcr.io/nrf24l01/sniffly/frontend:latest
    build:
      context: frontend/
      dockerfile: Dockerfile
      args:
        VITE_BACKEND_URL: "/api"
    env_file:
      - .env
    expose:
      - "8001"
    networks:
      - sniffly-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8001/"]
      interval: 10s
      retries: 30
      timeout: 3s
      start_period: 10s
    restart: always

  nginx:
    image: nginx:stable-alpine
    ports:
      - "${NGINX_BIND_IP}:${NGINX_BIND_PORT}:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:80/ng/ping"]
      interval: 10s
      retries: 30
      timeout: 3s
      start_period: 5s
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      frontend:
        condition: service_healthy
      backend:
        condition: service_healthy
      capture-receiver:
        condition: service_healthy
    networks:
      - sniffly-net
    restart: always

  postgres:
    image: timescale/timescaledb:latest-pg17
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: he1loT1ver
      POSTGRES_DB: postgres
    expose:
      - "5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./dump_snif.sql:/docker-entrypoint-initdb.d/dump_snif.sql:ro
    networks:
      - sniffly-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
    command: ["postgres", "-c", "listen_addresses=*"]

  redis:
    image: redis:8
    restart: unless-stopped
    expose:
      - "6379"
    networks:
      - sniffly-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 5s

  rabbitmq:
    image: rabbitmq:3-management
    restart: unless-stopped
    expose:
      - "5672"
      - "15672"
    environment:
      RABBITMQ_DEFAULT_USER: rmquser
      RABBITMQ_DEFAULT_PASS: rmqpass
    networks:
      - sniffly-net
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q check_running && rabbitmq-diagnostics -q check_port_connectivity"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s