name: Capture Receiver build

on:
  push:
    branches: [main]
    paths:
      - 'capture_receiver/**'
      - '.github/workflows/capture_receiver.yml'
  pull_request:
    branches: [main]
    paths:
      - 'capture_receiver/**'
      - '.github/workflows/capture_receiver.yml'
  workflow_dispatch:

env:
  LONG_IMAGE_TAG: ${{ github.sha }}

jobs:
  build-capture_receiver:
    name: Build Capture Receiver
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set short hash
        run: echo "IMAGE_TAG=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Set REPO_NAME env variable
        run: echo "REPO_NAME=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build image and push to GHCR
        uses: docker/build-push-action@v5
        with:
          context: capture_receiver
          tags: |
            ghcr.io/${{ env.REPO_NAME }}/capture_receiver:latest
            ghcr.io/${{ env.REPO_NAME }}/capture_receiver:${{ env.IMAGE_TAG }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max